; NSIS owns installer localization independently of the Electron application locale.
LangString INSTALLER_INSTALL ${LANG_ENGLISH} "Install now"
LangString INSTALLER_INSTALL ${LANG_SIMPCHINESE} "قيام أي تثبيت"
LangString INSTALLER_FINISH ${LANG_ENGLISH} "Finish"
LangString INSTALLER_FINISH ${LANG_SIMPCHINESE} "إتمام"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_ENGLISH} "Preparing installation… %d%%"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_SIMPCHINESE} "صحيح في دقيق تجهيز تثبيت… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_ENGLISH} "Extracting files… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_SIMPCHINESE} "صحيح في حل ضغط ملف… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_ENGLISH} "Installing files… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_SIMPCHINESE} "صحيح في تثبيت ملف… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_ENGLISH} "Finishing installation… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_SIMPCHINESE} "صحيح في إتمام تثبيت… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_ENGLISH} "Cleaning temporary files… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_SIMPCHINESE} "صحيح في تنظيف مؤقت ملف… %d%%"
LangString INSTALLER_CHOOSE_PATH ${LANG_ENGLISH} "Choose location"
LangString INSTALLER_CHOOSE_PATH ${LANG_SIMPCHINESE} "اختيار تثبيت موضع"
LangString INSTALLER_BROWSE ${LANG_ENGLISH} "Browse"
LangString INSTALLER_BROWSE ${LANG_SIMPCHINESE} "اختيار"
LangString INSTALLER_LAUNCH ${LANG_ENGLISH} "Launch now"
LangString INSTALLER_LAUNCH ${LANG_SIMPCHINESE} "قيام أي بدء"
LangString INSTALLER_LAUNCH_FAILED ${LANG_ENGLISH} "DeepSeek Harness could not be launched. Retry, or clear Launch now and close the installer."
LangString INSTALLER_LAUNCH_FAILED ${LANG_SIMPCHINESE} "لا يمكن بدء DeepSeek Harness. طلب إعادة محاولة، أو إلغاء ربط اختيار قيام أي بدء بعد إغلاق تثبيت برنامج."
LangString INSTALLER_UI_ERROR ${LANG_ENGLISH} "The installer could not initialize its window. Close it and try again."
LangString INSTALLER_UI_ERROR ${LANG_SIMPCHINESE} "لا يمكن ابتدائي تحويل تثبيت نافذة، طلب إغلاق بعد إعادة محاولة."
LangString INSTALLER_THEME_ERROR ${LANG_ENGLISH} "Use /THEME=auto, /THEME=light or /THEME=dark."
LangString INSTALLER_THEME_ERROR ${LANG_SIMPCHINESE} "رئيسي عنوان معامل يجب لـ /THEME=auto،/THEME=light أو /THEME=dark."
LangString INSTALLER_FAILED ${LANG_ENGLISH} "Installation did not finish. Close this installer and retry. If the problem persists, download the installer again."
LangString INSTALLER_FAILED ${LANG_SIMPCHINESE} "تثبيت لم إتمام، طلب إغلاق تثبيت برنامج بعد إعادة محاولة. مثل ما زال فشل، طلب إعادة تحت تحميل تثبيت حزمة."
LangString INSTALLER_RUNNING ${LANG_ENGLISH} "DeepSeek Harness is running. Close the application, then run this installer again."
LangString INSTALLER_RUNNING ${LANG_SIMPCHINESE} "DeepSeek Harness صحيح في تشغيل. طلب أولا إغلاق تطبيق، مجددا إعادة تشغيل تثبيت برنامج."
LangString INSTALLER_PATH_INVALID ${LANG_ENGLISH} "Choose a full local folder path. Drive roots, system folders, links and special characters are not supported."
LangString INSTALLER_PATH_INVALID ${LANG_SIMPCHINESE} "طلب اختيار محلي مغناطيس قرص فوق كامل ملف مشبك مسار، لا يستطيع استخدام مغناطيس قرص أصل دليل، نظام دليل، رابط دليل أو يتضمن خاص خاص محرف مسار."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_ENGLISH} "Choose an empty folder or the registered DeepSeek Harness installation folder."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_SIMPCHINESE} "طلب اختيار فارغ ملف مشبك، أو DeepSeek Harness أصل قدوم تثبيت دليل."
LangString INSTALLER_PATH_WRITABLE ${LANG_ENGLISH} "This location is not writable. Choose a folder available to the current user."
LangString INSTALLER_PATH_WRITABLE ${LANG_SIMPCHINESE} "لا يمكن كتابة هذا موضع. طلب اختيار حالي مستخدم يمكن كتابة ملف مشبك؛ تثبيت برنامج لن تقديم طلب إدارة عضو إذن."
LangString INSTALLER_DISK_SPACE ${LANG_ENGLISH} "There is not enough free disk space. Choose another location."
LangString INSTALLER_DISK_SPACE ${LANG_SIMPCHINESE} "هذا مغناطيس قرص متاح فضاء لا كاف، طلب اختيار أخرى موضع."
LangString INSTALLER_PER_USER ${LANG_ENGLISH} "This installer supports the current user only. Uninstall the existing all-users installation first."
LangString INSTALLER_PER_USER ${LANG_SIMPCHINESE} "هذا تثبيت برنامج فقط دعم حمل حالي مستخدم. طلب أولا إزالة قد لديه كل مستخدم تثبيت إصدار."
